export const ADD_EMAIL = 'ADD_EMAIL';

export const REQUEST_STARTED = 'REQUEST_STARTED';

export const REQUEST_SUCCESSFUL = 'REQUEST_SUCCESSFUL';

export const REQUEST_FAILED = 'REQUEST_FAILED';

export const ADD_EXPENSES = 'ADD_EXPENSES';
